{% set version = "0.9.10" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bsts
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bsts_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bsts/bsts_{{ version }}.tar.gz
  sha256: a302bc08d04ef8de83a7bf8dce03e949cadb423361bd85f9ad5dac77918271b1

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-boom >=0.9.11
    - r-boomspikeslab >=1.2.5
    - r-xts
    - r-zoo >=1.8
  run:
    - r-base
    - r-boom >=0.9.11
    - r-boomspikeslab >=1.2.5
    - r-xts
    - r-zoo >=1.8

test:
  commands:
    - $R -e "library('bsts')"           # [not win]
    - "\"%R%\" -e \"library('bsts')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=bsts
  license: LGPL-2.1-only
  summary: Time series regression using dynamic linear models fit using MCMC. See Scott and Varian (2014) <DOI:10.1504/IJMMNO.2014.059942>, among many other sources.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - Yue-Li-atBain
